/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package resortfrontdeskmanagementsystem1;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author OWNER
 */
public class booking extends javax.swing.JFrame {

    /**
     * Creates new form booking
     */
    public booking() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        bookingID = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        guestID = new javax.swing.JTextField();
        bookingDate = new javax.swing.JTextField();
        bookingType = new javax.swing.JComboBox<>();
        jsubmitbutton = new javax.swing.JButton();
        jclearbutton = new javax.swing.JButton();
        jaddListbutton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jbackbutton = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        number = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        peopleNumber = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        paymentMethod = new javax.swing.JComboBox<>();
        checkbox = new java.awt.Checkbox();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jLabel1.setText("Booking Form");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setText("Booking No. ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 110, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setText("Guest No.");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 110, 60, 20));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setText("Booking Date ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 330, -1, -1));
        getContentPane().add(bookingID, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 100, 60, 30));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel5.setText("Type of Booking");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 180, -1, -1));
        getContentPane().add(guestID, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 100, 60, 30));
        getContentPane().add(bookingDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 330, 280, -1));

        bookingType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "         ", "Online", "Walk-in" }));
        bookingType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookingTypeActionPerformed(evt);
            }
        });
        getContentPane().add(bookingType, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 180, 280, -1));

        jsubmitbutton.setText("Submit");
        jsubmitbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jsubmitbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(jsubmitbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 390, -1, -1));

        jclearbutton.setText("Clear");
        jclearbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jclearbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(jclearbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 390, -1, -1));

        jaddListbutton.setText("Add List");
        jaddListbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jaddListbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(jaddListbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 390, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Booking No.", "Guest No.", "Name", "Email", "Number", "Booking Date", "Type of Booking", "Number of People", "Payment Method"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 430, 870, 230));

        jbackbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbackbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(jbackbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 30, -1, 30));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel7.setText("Name");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 180, -1, -1));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel8.setText("Email");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 230, -1, -1));
        getContentPane().add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 180, 280, -1));
        getContentPane().add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 230, 280, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel6.setText("Number");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 280, -1, -1));
        getContentPane().add(number, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 280, 280, -1));

        jLabel9.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel9.setText("Number of People");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 230, -1, -1));
        getContentPane().add(peopleNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 230, 280, -1));

        jLabel10.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel10.setText("Payment Method");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 280, -1, -1));

        paymentMethod.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "              ", "Cash", "Credit", "Check" }));
        getContentPane().add(paymentMethod, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 280, 280, -1));

        checkbox.setBackground(java.awt.Color.lightGray);
        checkbox.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        checkbox.setLabel("Agreements to Terms and Conditions");
        getContentPane().add(checkbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 330, 270, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bg3.jpg"))); // NOI18N
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 710));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jsubmitbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jsubmitbuttonActionPerformed
        // TODO add your handling code here:
        String bookingNumber = bookingID.getText();
        String guestNumber = guestID.getText();
        String bookingDateValue = bookingDate.getText();
        String bookingTypeValue = (String) bookingType.getSelectedItem();
        
        if (bookingNumber.isEmpty() || guestNumber.isEmpty() || bookingDateValue.isEmpty() || bookingTypeValue.trim().equals("         ")) {
        JOptionPane.showMessageDialog(this, "Please fill all the fields correctly.", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            String submissionMessage = "Booking Number: " + bookingNumber + "\n"
                + "Guest Number: " + guestNumber + "\n"
                + "Booking Date: " + bookingDateValue + "\n"
                + "Booking Type: " + bookingTypeValue;
            
        JOptionPane.showMessageDialog(this, submissionMessage, "Booking Details Submitted", JOptionPane.INFORMATION_MESSAGE);
        
            bookingID.setText("");
            guestID.setText("");
            bookingDate.setText("");
            bookingType.setSelectedIndex(0);
        }
    }//GEN-LAST:event_jsubmitbuttonActionPerformed

    private void jclearbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jclearbuttonActionPerformed
        // TODO add your handling code here:
        bookingID.setText("  ");
        guestID.setText("  ");
        bookingDate.setText("  ");
        name.setText("  ");
        email.setText("  ");
        number.setText("  ");
        peopleNumber.setText("  ");
    }//GEN-LAST:event_jclearbuttonActionPerformed

    private void jaddListbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jaddListbuttonActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        model.addRow(new Object[]{bookingID.getText(), guestID.getText(),
                                    name.getText(), email.getText(),
                                    number.getText(), peopleNumber.getText(), paymentMethod.getSelectedItem(),
                                    bookingDate.getText(), bookingType.getSelectedItem()});
    }//GEN-LAST:event_jaddListbuttonActionPerformed

    private void jbackbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbackbuttonActionPerformed

        int response = JOptionPane.showConfirmDialog(this,
                "Do you want really to go back?",
                "Confirm",
                JOptionPane.YES_NO_OPTION);
        
        if (response == JOptionPane.YES_OPTION) {
            dispose();
            main m = new main ();
            m.setTitle("Go back to main");
            m.setLocationRelativeTo(null);
            m.setVisible(true);   
        } else {
            System.out.println ("User chose to stay on the current page.");
        }
        
    }//GEN-LAST:event_jbackbuttonActionPerformed

    private void bookingTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookingTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bookingTypeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new booking().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bookingDate;
    private javax.swing.JTextField bookingID;
    private javax.swing.JComboBox<String> bookingType;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private java.awt.Checkbox checkbox;
    private javax.swing.JTextField email;
    private javax.swing.JTextField guestID;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jaddListbutton;
    private javax.swing.JButton jbackbutton;
    private javax.swing.JButton jclearbutton;
    private javax.swing.JButton jsubmitbutton;
    private javax.swing.JTextField name;
    private javax.swing.JTextField number;
    private javax.swing.JComboBox<String> paymentMethod;
    private javax.swing.JTextField peopleNumber;
    // End of variables declaration//GEN-END:variables
}
