/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package resortfrontdeskmanagementsystem1;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author OWNER
 */
public class cancelbooking extends javax.swing.JFrame {

    /**
     * Creates new form cancellation
     */
    public cancelbooking() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cancellationID = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        bookingID = new javax.swing.JTextField();
        bookingDate = new javax.swing.JTextField();
        jbackbutton = new javax.swing.JButton();
        reason = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jaddListbutton = new javax.swing.JButton();
        jclearbutton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        number = new javax.swing.JTextField();
        checkbox1 = new java.awt.Checkbox();
        jsubmitbutton = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        refundAmount = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jLabel1.setText("Cancellation Form");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setText("Cancellation No.");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 100, -1, -1));
        getContentPane().add(cancellationID, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 90, 70, 30));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setText("Booking No.");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 100, -1, 20));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel6.setText("Booking Date");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 210, -1, -1));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel7.setText("Reason");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 270, -1, -1));
        getContentPane().add(bookingID, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 92, 70, 30));
        getContentPane().add(bookingDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 200, 280, -1));

        jbackbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbackbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(jbackbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 30, -1, 30));

        reason.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "                               ", "Can not make it.", "Change of travel plans.", "Health Issues", "Financial Problem", " " }));
        reason.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reasonActionPerformed(evt);
            }
        });
        getContentPane().add(reason, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 260, 280, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cancellation No.", "Booking No.", "Name", "Email", "Number", "Booking Date", "Reason", "Refund Amount"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 480, 800, 170));

        jaddListbutton.setText("Add to List");
        jaddListbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jaddListbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(jaddListbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 420, -1, -1));

        jclearbutton.setText("Clear");
        jclearbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jclearbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(jclearbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 430, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setText("Name");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 210, -1, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel5.setText("Number");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 330, -1, -1));
        getContentPane().add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 210, 280, -1));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel8.setText("Email");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 270, -1, -1));
        getContentPane().add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 270, 280, -1));
        getContentPane().add(number, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 330, 280, -1));

        checkbox1.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        checkbox1.setLabel("Agreements to Terms and Conditions");
        getContentPane().add(checkbox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 380, 260, -1));

        jsubmitbutton.setText("Submit");
        jsubmitbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jsubmitbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(jsubmitbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 420, -1, -1));

        jLabel10.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel10.setText("Refund Amount");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 330, -1, -1));
        getContentPane().add(refundAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 320, 280, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bg3.jpg"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jaddListbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jaddListbuttonActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        model.addRow(new Object[]{cancellationID.getText(), bookingID.getText(),
                                    name.getText(), email.getText(), number.getText(),refundAmount.getText(),
                                    bookingDate.getText(), reason.getSelectedItem()});
    }//GEN-LAST:event_jaddListbuttonActionPerformed

    private void jbackbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbackbuttonActionPerformed
                                 
        int response = JOptionPane.showConfirmDialog(this,
                "Do you want really to go back?",
                "Confirm",
                JOptionPane.YES_NO_OPTION);
        
        if (response == JOptionPane.YES_OPTION) {
            dispose();
            main m = new main ();
            m.setTitle("Go back to main");
            m.setLocationRelativeTo(null);
            m.setVisible(true);   
        } else {
            System.out.println ("User chose to stay on the current page.");
        }
        
    
    }//GEN-LAST:event_jbackbuttonActionPerformed

    private void jclearbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jclearbuttonActionPerformed
        // TODO add your handling code here:
        cancellationID.setText("  ");
        bookingID.setText("  ");
        bookingDate.setText("  ");
        name.setText("  ");
        email.setText("  ");
        number.setText("  ");
        refundAmount.setText("  ");
    }//GEN-LAST:event_jclearbuttonActionPerformed

    private void reasonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reasonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_reasonActionPerformed

    private void jsubmitbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jsubmitbuttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jsubmitbuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cancelbooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new cancelbooking().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bookingDate;
    private javax.swing.JTextField bookingID;
    private javax.swing.JTextField cancellationID;
    private java.awt.Checkbox checkbox1;
    private javax.swing.JTextField email;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jaddListbutton;
    private javax.swing.JButton jbackbutton;
    private javax.swing.JButton jclearbutton;
    private javax.swing.JButton jsubmitbutton;
    private javax.swing.JTextField name;
    private javax.swing.JTextField number;
    private javax.swing.JComboBox<String> reason;
    private javax.swing.JTextField refundAmount;
    // End of variables declaration//GEN-END:variables
}