package resortfrontdeskmanagementsystem1;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Maricris
 * 
 */
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.*;  
import database.*;


public class checkout extends javax.swing.JFrame {

    /**
     * Creates new form checkout
     */
    public checkout() {
        initComponents();
        jcustomername.setEditable(true);
        jemail.setEditable(true);
        jroomnumber.setEditable(true);
        jpriceperday.setEditable(true);
        jcheckindate.setEditable(true);
        jnumberdaysofstay.setEditable(true);
        jcheckoutdate.setEditable(false);
     
        SimpleDateFormat myFormat= new SimpleDateFormat("yyyy/MM/dd");
        Calendar cal= Calendar.getInstance();
        jcheckoutdate.setText(myFormat.format(cal.getTime()));

    }
    int id = 0;
    String Query;
    String roomandcottageType;
    String roomSize;
    String roomandcottageNumber;
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jemail = new javax.swing.JTextField();
        jsearchbutton = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jroomnumber = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jpriceperday = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jcheckindate = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jnumberdaysofstay = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jcheckoutdate = new javax.swing.JTextField();
        jcheckoutbutton = new javax.swing.JButton();
        jclearbutton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jbackbutton = new javax.swing.JButton();
        jcustomername = new javax.swing.JTextField();
        jsearch = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1100, 500));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Palatino Linotype", 1, 48)); // NOI18N
        jLabel1.setText("Check Out Form");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setText("Email:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 580, -1, -1));

        jemail.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        getContentPane().add(jemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 610, 150, -1));

        jsearchbutton.setText("Search");
        jsearchbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jsearchbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(jsearchbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 150, -1, -1));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel7.setText("Room and Cottage Number:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 150, -1, 30));

        jTextField7.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        getContentPane().add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 90, 150, 0));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel8.setText("Customer Name:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 220, -1, -1));

        jroomnumber.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        getContentPane().add(jroomnumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 150, 240, 30));

        jLabel9.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel9.setText("Price Per Day:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 290, -1, -1));

        jpriceperday.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        getContentPane().add(jpriceperday, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 320, 150, -1));

        jLabel10.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel10.setText("Check IN Date:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 370, -1, -1));

        jcheckindate.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        getContentPane().add(jcheckindate, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 400, 150, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel6.setText("Number Days Of Stay:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 440, -1, -1));

        jnumberdaysofstay.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        getContentPane().add(jnumberdaysofstay, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 470, 150, -1));

        jLabel11.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel11.setText("Check OUT Date (Today):");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 510, -1, -1));

        jcheckoutdate.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        getContentPane().add(jcheckoutdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 540, 150, -1));

        jcheckoutbutton.setText("Check Out");
        jcheckoutbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcheckoutbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(jcheckoutbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 680, -1, -1));

        jclearbutton.setText("Clear");
        jclearbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jclearbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(jclearbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 680, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Mobile Number", "Email", "ID Proof", "Address", "Check In Date", "Room and Cottage Types", "Room and Cottage Number", "Price Per Day"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 200, 660, 440));

        jbackbutton.setText("Home");
        jbackbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbackbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(jbackbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 40, -1, 20));

        jcustomername.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        getContentPane().add(jcustomername, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 250, 150, -1));

        jsearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/formsbg.png"))); // NOI18N
        jsearch.setText("jLabel4");
        getContentPane().add(jsearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1360, 760));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jclearbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jclearbuttonActionPerformed
        // TODO add your handling code here:
        jcustomername.setText("");
        jemail.setText("");
        jTextField7.setText("");
        jroomnumber.setText("");
        jpriceperday.setText("");
        jcheckindate.setText("");
        jnumberdaysofstay.setText("");
        jcheckoutdate.setText("");
        
    }//GEN-LAST:event_jclearbuttonActionPerformed

    private void jcheckoutbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcheckoutbuttonActionPerformed
        // TODO add your handling code here:
         String email = jemail.getText();
         String name = jcustomername.getText();
         String mobileNumber = jTextField7.getText();
         String roomNumber = jroomnumber.getText();
         String pricePerDay = jpriceperday.getText();
         String checkInDate = jcheckindate.getText();
         String numberdaysofstay = jnumberdaysofstay.getText();
         String checkoutdate = jcheckoutdate.getText();
         
         if (name.isEmpty() || email.isEmpty() || mobileNumber.isEmpty() || roomNumber.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please fill in all required fields.");
            return; // Stop the execution if validation fails
        }
         
          DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{
            id, name, mobileNumber, email, "ID Proof", "Address", checkInDate, "Room Type", roomNumber, pricePerDay
        });
        
        JOptionPane.showMessageDialog(null, "Checkout Complete!");


    }//GEN-LAST:event_jcheckoutbuttonActionPerformed

    private void jbackbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbackbuttonActionPerformed
        int response = JOptionPane.showConfirmDialog(this,
                "Do you want really to go back?",
                "Confirm",
                JOptionPane.YES_NO_OPTION);
        
        if (response == JOptionPane.YES_OPTION) {
            dispose();
            main m = new main ();
            m.setTitle("Go back to main");
            m.setLocationRelativeTo(null);
            m.setVisible(true);   
        } else {
            System.out.println ("User chose to stay on the current page.");
        }
        
    }//GEN-LAST:event_jbackbuttonActionPerformed

    private void jsearchbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jsearchbuttonActionPerformed
       String customerName = jcustomername.getText();
       String email = jemail.getText();
       
        String query = "SELECT * FROM customer WHERE checkOut IS NULL";
        
        if (!customerName.isEmpty()) {
        query += " AND customerName LIKE '%" + customerName + "%'";
       }
       if (!email.isEmpty()) {
        query += " AND email LIKE '%" + email + "%'";
       }
       
       DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
       model.setRowCount(0); 
       
        try {
        // Execute the query
        ResultSet rs = Select.getData(query);
        
        // Populate the JTable with data from the ResultSet
        while (rs.next()) {
            model.addRow(new Object[]{
                rs.getString(1),  // Customer ID
                rs.getString(2),  // Customer Name
                rs.getString(3),  // Address
                rs.getString(4),  // Contact Number
                rs.getString(5),  // Email
                rs.getString(6),  // Check-in Date
                rs.getString(7),  // Check-out Date
                rs.getString(8),  // Room Number
                rs.getString(9),  // Number of Days
                rs.getString(10), // Price per Day
                rs.getString(11), // Total Price
                rs.getString(12)  // Status
            });
            
             }
        rs.close();  // Don't forget to close the ResultSet
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
    }
       
       
    }//GEN-LAST:event_jsearchbuttonActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
       ResultSet rs = Select.getData("SELECT * FROM customer WHERE checkOut IS NULL");
       DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
       try
       {
          while (rs.next()) {
            model.addRow(new Object[] {
                rs.getString(1),  
                rs.getString(2), 
                rs.getString(3), 
                rs.getString(4),  
                rs.getString(5),  
                rs.getString(6),  
                rs.getString(7),  
                rs.getString(8),  
                rs.getString(9),  
                rs.getString(10), 
                rs.getString(11), 
                rs.getString(12)
            });
       }
          rs.close();
       }
        catch (Exception e) {
        JOptionPane.showMessageDialog(null, e);
    }
    }//GEN-LAST:event_formComponentShown

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(checkout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(checkout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(checkout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(checkout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new checkout().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JButton jbackbutton;
    private javax.swing.JTextField jcheckindate;
    private javax.swing.JButton jcheckoutbutton;
    private javax.swing.JTextField jcheckoutdate;
    private javax.swing.JButton jclearbutton;
    private javax.swing.JTextField jcustomername;
    private javax.swing.JTextField jemail;
    private javax.swing.JTextField jnumberdaysofstay;
    private javax.swing.JTextField jpriceperday;
    private javax.swing.JTextField jroomnumber;
    private javax.swing.JLabel jsearch;
    private javax.swing.JButton jsearchbutton;
    // End of variables declaration//GEN-END:variables
}
