/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package resortfrontdeskmanagementsystem1;
  
import Database.signuplogindb;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.ResultSet;

/**
 *
 * @author djani
 */
public class login extends javax.swing.JFrame {

    public login() {
        initComponents();
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        juname = new javax.swing.JTextField();
        jpass = new javax.swing.JPasswordField();
        jloginbutton = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jsignupbutton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jshowpass = new javax.swing.JCheckBox();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Microsoft PhagsPa", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 0));
        jLabel1.setText("RECEPTIONIST");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 160, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Username:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 250, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Password:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 330, 71, -1));

        juname.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getContentPane().add(juname, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 280, 320, -1));

        jpass.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpassActionPerformed(evt);
            }
        });
        getContentPane().add(jpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 360, 320, -1));

        jloginbutton.setBackground(new java.awt.Color(153, 255, 153));
        jloginbutton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jloginbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/key_1.png"))); // NOI18N
        jloginbutton.setText("LOGIN");
        jloginbutton.setBorder(null);
        jloginbutton.setIconTextGap(5);
        jloginbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jloginbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(jloginbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 450, 320, 38));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("New Receptionist?");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 560, -1, 30));

        jsignupbutton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jsignupbutton.setForeground(new java.awt.Color(0, 204, 51));
        jsignupbutton.setText("SIGNUP");
        jsignupbutton.setBorder(null);
        jsignupbutton.setContentAreaFilled(false);
        jsignupbutton.setFocusPainted(false);
        jsignupbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jsignupbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(jsignupbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 560, 90, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/minilogo.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 120, 110));

        jLabel5.setFont(new java.awt.Font("Microsoft PhagsPa", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 153, 0));
        jLabel5.setText("LOGIN");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 190, 60, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/recep.png"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 80, -1, -1));

        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1300, 60, -1, -1));

        jLabel10.setText("jLabel10");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 200, -1, -1));

        jLabel9.setText("jLabel9");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1320, 110, -1, -1));

        jLabel11.setText("jLabel11");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, 80, -1, -1));

        jButton1.setText("jButton1");
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 10, -1, -1));

        jshowpass.setText("Show password");
        jshowpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jshowpassActionPerformed(evt);
            }
        });
        getContentPane().add(jshowpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 400, -1, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/loginbg.png"))); // NOI18N
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jloginbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jloginbuttonActionPerformed

            String username = juname.getText();
            String password = String.valueOf(jpass.getPassword());
            
            if (username.isEmpty()|| password.isEmpty()) {
                JOptionPane.showMessageDialog(jLabel12, "Username/Password should not be empty", "ERROR", JOptionPane.ERROR_MESSAGE);
            }else {
                receptionistLogin(username,password);
            }
          
    }//GEN-LAST:event_jloginbuttonActionPerformed

    private void jsignupbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jsignupbuttonActionPerformed
        dispose();
        signup s = new signup();
        s.setTitle("Signup a new receptionist");
        s.setLocationRelativeTo(null); //center the form
        s.setVisible(true);
    }//GEN-LAST:event_jsignupbuttonActionPerformed

    private void jpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jpassActionPerformed

    private void jshowpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jshowpassActionPerformed
        // TODO add your handling code here:
           if (jshowpass.isSelected()) {
            jpass.setEchoChar((char) 0); // Show the password (no mask)
        } else {
            jpass.setEchoChar('*'); // Mask the password with '*'
        }
    }//GEN-LAST:event_jshowpassActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton jloginbutton;
    private javax.swing.JPasswordField jpass;
    private javax.swing.JCheckBox jshowpass;
    private javax.swing.JButton jsignupbutton;
    private javax.swing.JTextField juname;
    // End of variables declaration//GEN-END:variables

    private void receptionistLogin(String username, String password) {
        Connection dbconn = signuplogindb.connectDB();
        if(dbconn !=null){
        try {
            PreparedStatement st = (PreparedStatement)
                    dbconn.prepareStatement("Select * from receptionist WHERE username = ? AND password = ? ");
            
            st.setString(1, username);
            st.setString(2, password);
            ResultSet res = st.executeQuery();
            if(res.next()){
                dispose();
                main m = new main();
                m.setTitle("main");
                m.setVisible(true);  
            }else {
                System.out.println("username " + username);
                System.out.println("password " + password);
                JOptionPane.showMessageDialog(jLabel12, "Username/Password is not found", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
        } catch (SQLException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        }else{
                System.out.println("The connection is not available");
                }
            
    }
}